apiVersion: v1
kind: Service
metadata:
  name:  sdp
  namespace: dev-xibar
spec:
  selector:
    app: sdp
  ports:
  - protocol: TCP
    port: 37804
    targetPort: 37804
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdp
  namespace: dev-xibar
  labels:
    app: sdp
spec:
  strategy:
      type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: sdp
  template:
    metadata:
      labels:
        app: sdp
    spec:
      imagePullSecrets:
      - name: regkano
      volumes:
      - name: sdp-config-volume
        secret:
          secretName: xibar-module-config  
      containers:
      - name: sdp
        image: registry.kanosolution.net/sebar/sdp/sdp:dev.deploy
        imagePullPolicy: Always
        ports:
        - containerPort: 37804
        volumeMounts:
        - name: sdp-config-volume
          mountPath: /app/config
          readOnly: true
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.25"