Hosts:
  v1/fico: :37820
Connections:
  tenant:
    Txt: ${env:db_conn_tenant}
    PoolSize: 500
EventServer:
  Server: ${env:event_conn}
  Group: ${env:event_group}
  EventChangeTopic: /config/change
Data:
  data_folder: ${ctx:wd}/data
  topic_asset_write: /v1/asset/write
  addr_asset_view: ${env:xibar_base_host}/v1/asset/view
  topic_send_message_template: /v1/msg/send-template
  topic_change_session_data: /v1/iam/auth/change-data
  addr_web_user: ${env:xibar_base_host}/app
  addr_web_tenant: ${env:xibar_base_host}/app
  addr_web_admin: ${env:xibar_base_host}/app
  addr_web_user_activation: /activate-user
  pdf_exe_path: D:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe
  pdf_template_path: template/pdf
