apiVersion: v1
kind: Service
metadata:
  name:  tenant
  namespace: dev-xibar
spec:
  selector:
    app: tenant
  ports:
  - protocol: TCP
    port: 37800
    targetPort: 37800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant
  namespace: dev-xibar
  labels:
    app: tenant
spec:
  strategy:
      type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      imagePullSecrets:
      - name: regkano
      volumes:
      - name: tenant-config-volume
        secret:
          secretName: xibar-module-config  
      containers:
      - name: tenant
        image: registry.kanosolution.net/sebar/tenantcore/tenant:dev.deploy
        imagePullPolicy: Always
        ports:
        - containerPort: 37800
        volumeMounts:
        - name: tenant-config-volume
          mountPath: /app/config
          readOnly: true
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.25"