apiVersion: v1
kind: Service
metadata:
  name:  tenant
  namespace: dev-xibar
spec:
  selector:
    app: xibar-app
  ports:
  - protocol: TCP
    port: 37800
    targetPort: 37800
---
apiVersion: v1
kind: Service
metadata:
  name:  fico
  namespace: dev-xibar
spec:
  selector:
    app: xibar-app
  ports:
  - protocol: TCP
    port: 37801
    targetPort: 37801
---
apiVersion: v1
kind: Service
metadata:
  name:  kara
  namespace: dev-xibar
spec:
  selector:
    app: xibar-app
  ports:
  - protocol: TCP
    port: 37870
    targetPort: 37870
---
apiVersion: v1
kind: Service
metadata:
  name:  scm
  namespace: dev-xibar
spec:
  selector:
    app: xibar-app
  ports:
  - protocol: TCP
    port: 37802
    targetPort: 37802
---
apiVersion: v1
kind: Service
metadata:
  name:  mfg
  namespace: dev-xibar
spec:
  selector:
    app: xibar-app
  ports:
  - protocol: TCP
    port: 37803
    targetPort: 37803
---
apiVersion: v1
kind: Service
metadata:
  name:  sdp
  namespace: dev-xibar
spec:
  selector:
    app: xibar-app
  ports:
  - protocol: TCP
    port: 37804
    targetPort: 37804
---
apiVersion: v1
kind: Service
metadata:
  name:  she
  namespace: dev-xibar
spec:
  selector:
    app: xibar-app
  ports:
  - protocol: TCP
    port: 37930
    targetPort: 37930
---
apiVersion: v1
kind: Service
metadata:
  name:  bagong
  namespace: dev-xibar
spec:
  selector:
    app: xibar-app
  ports:
  - protocol: TCP
    port: 37890
    targetPort: 37890