apiVersion: v1
kind: Service
metadata:
  name:  bagong
  namespace: stg-bagong
spec:
  selector:
    app: bagong
  ports:
  - protocol: TCP
    port: 37890
    targetPort: 37890
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bagong
  namespace: stg-bagong
  labels:
    app: bagong
spec:
  strategy:
      type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: bagong
  template:
    metadata:
      labels:
        app: bagong
    spec:
      imagePullSecrets:
      - name: regkano
      volumes:
      - name: bagong-config-volume
        secret:
          secretName: xibar-module-config  
      containers:
      - name: bagong
        image: registry.kanosolution.net/sebar/bagong/bagong:stg.deploy
        imagePullPolicy: Always
        ports:
        - containerPort: 37890
        volumeMounts:
        - name: bagong-config-volume
          mountPath: /app/config
          readOnly: true
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.25"