apiVersion: v1
kind: Service
metadata:
  name:  web-bagong
  namespace: stg-bagong
spec:
  selector:
    app: web-bagong
  ports:
  - protocol: TCP
    port: 38001
    targetPort: 38001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-bagong
  namespace: stg-bagong
  labels:
    app: web-bagong
spec:
  strategy:
      type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: web-bagong
  template:
    metadata:
      labels:
        app: web-bagong
    spec:
      imagePullSecrets:
      - name: regkano
      containers:
      - name: web-bagong
        image: registry.kanosolution.net/sebar/bagong-web/web-app:stg.deploy
        imagePullPolicy: Always
        ports:
        - containerPort: 38001