apiVersion: v1
kind: Service
metadata:
  name:  mfg
  namespace: stg-bagong
spec:
  selector:
    app: mfg
  ports:
  - protocol: TCP
    port: 37803
    targetPort: 37803
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfg
  namespace: stg-bagong
  labels:
    app: mfg
spec:
  strategy:
      type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: mfg
  template:
    metadata:
      labels:
        app: mfg
    spec:
      imagePullSecrets:
      - name: regkano
      volumes:
      - name: mfg-config-volume
        secret:
          secretName: xibar-module-config  
      containers:
      - name: mfg
        image: registry.kanosolution.net/sebar/mfg/mfg:stg.deploy
        imagePullPolicy: Always
        ports:
        - containerPort: 37800
        volumeMounts:
        - name: mfg-config-volume
          mountPath: /app/config
          readOnly: true
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.25"